#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 version1 [version2 ...]"
    exit 1
fi

versions=("$@")

while true; do
    clear
    python medical_image_segmentation/analyze_data/plot_metrics_in_terminal.py \
        --metrics online_knn_val_acc \
        --files $(printf "logs/lightning_logs/version_%s/metrics.csv " "${versions[@]}")
    sleep 30
done
