#!/bin/bash
apptainer exec --nv docker/ffcv-ssl_latest.sif \
bash -c "source activate; \
conda activate ffcv-ssl; \
python medical_image_segmentation/train/train_ssl.py \
    --image_size 56 \
    --batch_size 512 \
    --float_matmul_precision medium \
    --epochs 1000 \
    --val_every 1"

