#!/bin/bash
apptainer exec /scratch/gpfs/eh0560/repos/medical-image-segmentation/docker/ffcv-ssl_latest.sif \
bash -c "source activate; \
conda activate ffcv-ssl; \
python /scratch/gpfs/eh0560/repos/medical-image-segmentation/medical_image_segmentation/analyze_data/compute_ffcv_dataset_metrics.py \
--beton_path /scratch/gpfs/RUSTOW/med_datasets/ffcv_datasets/test_radiology_1M.beton"
