#!/bin/bash
module purge
module load anaconda3/2023.9
conda activate medical_image_segmentation
cd /scratch/gpfs/eh0560/repos/medical-image-segmentation
python \
/scratch/gpfs/eh0560/repos/medical-image-segmentation/medical_image_segmentation/analyze_data/create_subset.py \
dicom_sizes \
--dirs /scratch/gpfs/eh0560/data/med_datasets /scratch/gpfs/RUSTOW/med_datasets \
--output_path /scratch/gpfs/eh0560/repos/medical-image-segmentation/data/dicom_image_analysis_info/dicom_image_dimensions.json